config/routes.rb
Rails.application.routes.draw do

  resources :locations, only: [:create, :update, :show, :destroy] do
    resources :visits, only: [:create, :update, :index, :destroy]
  end
  
  resources :users, only: [:create, :update, :show, :destroy] do
    resources :visits, only: [:create, :update, :index, :destroy]
  end
  resource :search, :only => :create

end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :visits
	belongs_to :user

	validates :name, :city, presence: true
	validates :name, uniqueness: true
	def self.iron_find (value)
		Location.where(id: value).first
	end

	scope :last_created, ->(value) { Location.last(value) }

	def self.in_spain? 
		if Location.country == 'Spain'
			
		end
	end

	def total_number_visits_month(month, year)
		return nil if month == nil or year == nil
		date_start = Time.new(year, month, 1)
		date_end = date_start + 1.month - 1.day
		visits_month = self.visits.where(from_date: date_start..date_end)
		visits_month.length
	end
end

app/models/search.rb
class Search
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :query, :field

  def execute!
    case self.field
    when "users"
      return User.where("username ILIKE '%#{self.query}%'")
    when "locations"
      return Location.where("name ILIKE '%#{self.query}%'")
    end
  end

  def persisted?
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :email, :firstname, :lastname, presence: true
  has_secure_password validations: false
  has_many :visits
  has_many :locations
end

app/models/visit.rb
class Visit < ActiveRecord::Base
	belongs_to :location
	belongs_to :user
	scope :last_created, ->(value) { Visit.last(value) }

	validates :user_id, :from_date, :to_date, :location_id, presence: true
	validate :from_date_is_in_the_future
	validate :to_date_is_before_from_date

	def from_date_is_in_the_future
		if from_date.to_i < Time.now.to_i
			errors.add(:from_date, "is in the past!")
		end
	end

	def to_date_is_before_from_date
		if from_date.to_i > to_date.to_i
			errors.add(:to_date, "is before from_date")
		end
	end
end

app/controllers/application_controller.rb
require 'json'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    redirect_to location_visits_path(params[:id])
  end

  def create
    location = Location.new location_params
    if location.save
      render text: {process: "SAVED"}.to_json
    else
      render text: {process: "ERROR"}.merge(location.errors.messages).to_json, status: 500
    end
  end

  def update
    location = Location.find(params[:id])
    location.update_attributes location_params
    render text: {process: "UPDATED"}.merge(location.attributes).to_json
  rescue
    render text: {process: "ERROR"}.merge(location.errors.messages).to_json, status: 500
  end

  def destroy
    location = Location.find(params[:id])
    location.destroy
    render text: {process: "DELETED"}.to_json
  rescue
    render text: {process: "ERROR"}.merge(location.errors.messages).to_json, status: 500
  end

  def location_params
      params.require(:location).permit(:name, :city, :country, :description, :zip_code, :street, :user_id)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def create
    search = Search.new
    search.query = search_params["query"]
    search.field = search_params["field"]
    @results = search.execute!
    return render 'index' unless @results.nil?
    render text: {search_results: "FieldError: Try with 'locations' OR 'users'"}.to_json
  end

  private
  def search_params
    params.require(:search).permit(:query, :field)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def create
    user = User.new user_params
    if user.save
      render text: {process: "SAVED"}.to_json
    else
      render text: {process: "ERROR"}.merge(user.errors.messages).to_json, status: 500
    end
  end

  def update
    user = User.find(params[:id])
    user.update_attributes user_params
    render text: {process: "UPDATED"}.merge({user: user.attributes}).to_json
  rescue ActiveRecord::RecordNotFound
    render text: "RecordNotFound!", status: 400
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    render text: {process: "DELETED"}.to_json
  rescue ActiveRecord::RecordNotFound
    render text: "RecordNotFound!", status: 400
  end

private
  def user_params
    params.require(:user).permit(:username, :firstname, :lastname, :email, :password)
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def index
    @location = Location.find(params[:location_id])
    @visits = Visit.all
  rescue ActiveRecord::RecordNotFound
    render text: 'NOT FOUND', status: 404
  end

  def create
    location = Location.find(params[:location_id])
    visit = location.visits.new visit_params
    if visit.save
      render text: {process: "SAVED"}.to_json
    else
      render text: {process: "ERROR"}.merge(visit.errors.messages).to_json, status: 500
    end
  end

  def destroy
    visit = Visit.find(params[:id])
    visit.destroy
    render text: {process: "DELETED"}.to_json
  rescue
    render text: {process: "ERROR"}.merge(visit.errors.messages).to_json, status: 500
  end

  def update
    visit = Visit.find(params[:id])
    visit.update_attributes visit_params
    render text: {process: "UPDATED"}.merge({user: user.attributes}).to_json
  rescue
    render text: {process: "ERROR"}.merge(visit.errors.messages).to_json, status: 500
  end

  private
  def visit_params
    params.require(:visit).permit(:user_id, :from_date, :to_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def notice
    flash[:notice] if flash[:notice]
  end

  def alert
    flash[:alert] if flash[:alert]
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def show_login_or_logout
    render template: user_signed_in? ? "/users/sessions/logout" : "/users/sessions/new"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeetMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
    <section class="login"><%= show_login_or_logout %></section>
</nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<nav>
    <section>
    </section>
</nav>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<% if @location.errors.any? %>
    <ul>
        <%= @location.errors.size %>
        <% @location.errors.full_messages.each do |error_message| %>
            <li><%= error_message %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for [@location] do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br />
    <%= f.label :city %>
    <%= f.text_field :city %>
    <br />
    <%= f.label :street %>
    <%= f.text_field :street %>
    <br />
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
    <br />
    <%= f.label :country %>
    <%= f.text_field :country %>
    <br />
    <%= f.label :description %>
    <%= f.text_field :description %>
    <br />
    <%= f.submit "Save" %>
    <%= f.button "Cancel", :name => "cancel" %>
<% end %>
 

app/views/locations/edit.html.erb
<%= render 'form' %>

app/views/locations/index.html.erb
<h1>All Locations</h1>
<ul>
	<% @locations.each do |location|  %>
	<% if location.name.present? %>
		<li><%= link_to location.name, location_path(location) %> - <%= location.city %> <%= link_to "Edit", edit_location_path(location) %> <%= link_to "Delete", location_path(location), method: 'Delete' %> </li>
	<% end %>
<% end %>
</ul>
<%= link_to "Back to the Welcome page", root_path %> <%= link_to "Create a new location", new_location_path %>

app/views/locations/new.html.erb
<%= render 'form' %>

app/views/locations/not_found.html.erb
<h1>NOT FOUND</h1>

app/views/locations/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<ul>
		<li><%= @location.name %> -- <span><%= @location.description %></span> - <span><%= @location.city %></span> <%= @location.zip_code %></span> - <span><%= @location.country %></span> <%= link_to "See the visits", location_visits_path(@location) %> <%= link_to "Create another visit", new_location_visit_path(@location) %></li>
	</ul>
<%= link_to "Back to all locations...", locations_path %>
</body>
</html>